### PR TITLE
Update running-postgraphile-in-docker.md

### PR DESCRIPTION
**Pull request by kevinmamaqi**
Include tslib as it throws an error if not installed.

## Checklist

- [ ] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

### CODE REVIEW

**Comment by benjie** [comment]
I don’t understand why this is necessary; tslib is an explicit dependency of PostGraphile: https://github.com/graphile/postgraphile/blob/main/package.json#L78

Will have to investigate.

**Comment by kevinmamaqi** [comment]
Hi @benjie,

I received an error related with the plugin the tslib was missing. I had to include it to make it work.

**Comment by benjie** [comment]
Sorry @kevinmamaqi I was on my phone so didn't reply in enough detail; what I mean is that this shouldn't be necessary. That it is indicates something is going wrong - so thanks for bringing the issue to my attention and I will try and figure out what's going wrong and address it within the packages themselves :+1:

**Comment by benjie** [comment]
Turns out this is a dependency bug in postgraphile-plugin-connection-filter that only seems to surface when the packages are installed globally (`npm install -g`) because `tslib` is not hoisted from PostGraphile in this case and thus the dependencies are not shared. I've filed an issue about it:

https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/164

Thanks for making me aware of the issue :pray:

**Comment by benjie** [comment]
This issue is now resolved: https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/164 👍

**Pull request closed without merging**
