### PR TITLE
Query Builder Mutation Example Formating

### PR DESCRIPTION
**Pull request by Reaper45**

### CODE REVIEW

**Comment by benjie** [comment]
I don't think this is correct; refer to this page in the gatsby docs:

https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#line-highlighting

Their example has no space:

````
```javascript{1,4-6}
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        `gatsby-remark-prismjs`,
      ]
    }
  }
]
```
````

What's the formatting issue you're seeing? (Perhaps you could upload a screenshot.)

**Comment by Reaper45** [comment]
There is no syntax highlighting without the the spacing.

**Comment by benjie** [comment]
That's not what I'm seeing:
Screenshot_20191013_110546

**Comment by benjie** [comment]
Please could you show me what you're seeing (and maybe share additional information such as which browser you're using, whether you have an ad-blocker or similar that might prevent loading the relevant highlighting code, etc)?

**Comment by benjie** [comment]
_[semi-automated message]_ Hi, there has been no activity in this issue for a while so I'm closing it to keep the issues/pull requests manageable. If this is still an issue, please re-open with additional details.

**Pull request closed without merging**
