### PR TITLE
Added link to learn.graphile.org to top menu

### PR DESCRIPTION
**Pull request by garcianavalon**
Looks like this on desktop and mobile

Screenshot 2019-12-02 at 11 44 50

Screenshot 2019-12-02 at 11 44 59

### CODE REVIEW

**Comment by jemgillam** [comment]
Looks like this on a smaller screen.

Screenshot 2019-12-02 at 11 04 04

Instead of using `POSTGRAPHILE_ROUTES` could you move this up into the block for the root pages instead. It'll then show on the index page instead of adding to the nav for the PostGraphile pages. 

You could also add a link in the footer under "resources".

Thanks

**Comment by garcianavalon** [comment]
on it!

**Comment by garcianavalon** [comment]
@jemgillam suggestions implemented. Let me know if it looks ok now in your screen

I haven't added an icon to learn in the footer, any suggestion on which one could work?

**Comment by jemgillam** [comment]
Maybe the graduation cap? https://fontawesome.com/icons/graduation-cap?style=solid

Otherwise, looking good 🙂

**Comment by garcianavalon** [comment]
- Added the icon to learn footer
- Reviewed in all screen sizes from mobile to 4k 😄 

Screenshot 2019-12-03 at 10 37 56
Screenshot 2019-12-03 at 10 38 06
Screenshot 2019-12-03 at 10 38 40
Screenshot 2019-12-03 at 10 38 47
Screenshot 2019-12-03 at 10 38 56
Screenshot 2019-12-03 at 10 39 00
Screenshot 2019-12-03 at 10 39 09
Screenshot 2019-12-03 at 10 39 13
Screenshot 2019-12-03 at 10 39 25
Screenshot 2019-12-03 at 10 39 30

**Comment by jemgillam** [comment]
LGTM 👍

**Pull request merged**
